---
title: "Exercise_02"
output: html_notebook
---

```{r}
#EXERCISE 1
#Evaluate the expected values, E[X], and the variance, V ar(X), for both methods

#install.packages("devtools")                  #eventually to install to have modi
#devtools::install_github("martinSter/modi")

library(modi)
x<-c(15.58,15.9,16,16.1,16.2)
p1<-c(0.15,0.21,0.3,0.15,0.14)
p2<-c(0.14,0.05,0.64,0.08,0.09)

p1_mean <- weighted.mean(x,p1)
p2_mean <- weighted.mean(x,p2)

p1_var <- weighted.var(x,p1)
p2_var <- weighted.var(x,p2)


sprintf("mean calculated with p1 method: %f",p1_mean)
sprintf("mean calculated with p2 method: %f",p2_mean)

sprintf("variance calculated with p1 method: %f",p1_var)
sprintf("variance calculated with p2 method: %f",p2_var)
```









```{r}
#EXERCISE 2
#simulate the waiting time for 50 people at the doctor’s office and plot the relative histogram
l=1/30
sim_data <- rexp(50,l)
hist(sim_data,main="Histogram of waiting time at the doctor",breaks=20, col = 'skyblue3')
grid()
```
```{r}
#what is the probability that a person will wait for less than 10 minutes ?
sprintf("The probability that a person will wait for less than 10 minutes is: %f",pexp(10, l, lower.tail=TRUE))

```

```{r}
#evaluate the average waiting time from the simulated data and compare it with the expected value (calculated from theory and by manipulating the probability distributions using R)
sprintf("The average waiting time from the simulated data : %f",mean(sim_data))
sprintf("Theoretical value : %f",1/l)   #is that correct? should i do something more sophisticated?
```
```{r}
#what is the probability for waiting more than one hour before being received ?
sprintf("The probability that a person will wait for more than 1 hour is: %f",pexp(60, l, lower.tail=FALSE))
```








```{r}
#EXERCISE 3
#If the number of errors follows a Poisson distribution, plot the pdf and cdf, and calculate the probability that there is at least one error on a specific page of the book
x <- 0:6
lambda <- 1/3
plot(x, dpois(x, lambda), type='b', col="navy", lwd=2, main="probability density function", ylab="probability", xlab="number of errors")
grid()
plot(x, ppois(x, lambda), type='b', col="navy", lwd=2, main="cumulative density function", ylab="cumulative sums", xlab="number of errors")
grid()


sprintf("The probability that there is at least one error on a specific page is : %f",ppois( 1,lambda, lower.tail=FALSE))
```










```{r}
#EXERCISE 4
#Calculate the probability that at least 10 draws are needed.

ap <- dbinom(1,10,1/13)
sprintf("the probability that at least 10 draws are needed is: %f", 1-ap)
```









```{r}
#EXERCISE 5
#using the integrate() R function, determine the constant c (and verify it analytically)
f <- function(x, c=1){ (x < 1)*(0)+(1 < x & x < 2)*(c*(x-1)*(2-x))+(x>2)*(0)}

int <- integrate(f=f,lower=1,upper=2)
sprintf("c parameter is equal to : %f",1/int$value)

#verify if the pdf is normalized:
sprintf("Integral of function: %f",integrate(f,lower=1,upper=2, c=1/int$value)$value)
```
```{r}
#write the set of four R functions and plot the pdf and cdf, respectively
#install.packages("GoFKernel")
library(GoFKernel)

#probability density function
df <- function(x){(x < 1)*(0)+(1 < x & x < 2)*(1/int$value*(x-1)*(2-x))+(x>2)*(0)}
plot(df,xlim=c(0,3), ylim = c(-1, 4), col = "red",  xlab="Time [Hours]", ylab = "df(x)",main = "Probability density function") 
grid()

#cumulative density function 
cf <- function(x){
  y <- c()
  for (i in x) {
    y <- append(y,integrate(df, lower = 1, upper = i)$value)
  }
  return(y)
}




#to plot the cdf function I need to generate a discrete interval
x<-seq(from = 1, to = 2, length = 100 )
plot(x,cf(x), type="l", col="red", xlab="Time [Hours]", main = "Cumulative density function")
grid()


#cumulative density function
inverse <- function (f, lower = 1, upper = 2) {function (y) uniroot((function (x) f(x) - y), lower = lower, upper = upper)[1]}   #the inverse of a function 
qf <- inverse(function(x) {integrate(df, lower = 1, upper = x)$value})  


#sampling function
rf <- function(nsamples){                             #return a vector with samples following the pdf
  y <- c()
  for (i in 1:nsamples){
    u <- runif(1,0,1)
    y[i]<-qf(u)$root
    }
  return(y)
}
hist(rf(10000),breaks=30, xlab = "Time [Hours]", main = "Histogram of 1000 simulated samples following the PDF",  col = 'skyblue3')    #an histo to check if it is following correctly the pdf 


```

```{r}
#evaluate the probability that the student will finish the aptitude test in more than 75 minutes. And that it will take 90 and 120 minutes.
proba <- integrate(df, lower=1.25, upper=Inf)
proba2 <- integrate(df, lower = 1.5, upper = 2)

sprintf("the probability that the student will finish in more than 75 minutes : %f", proba$value)
sprintf("The probability that it will take 90 and 120 minutes is: %f", proba2$value)
```









```{r}
#EXERCISE 6 
#write the set of four R functions and plot the pdf and cdf, respectively

#probability density function (already normalized)
df_2 <- function(x){(x < 1)*(0)+(1 < x & x < 2)*(2/(x**2))+(x>2)*(0)}
plot(df_2,xlim=c(0,3), ylim = c(-1, 4), col = "red", xlab="Space [Km]", ylab = "df(x)",main = "Probability density function") 
grid()


#cumulative density function 
cf_2 <- function(x){
  y <- c()
  for (i in x) {
    y <- append(y,integrate(df_2, lower = 1, upper = i)$value)
  }
  return(y)
}
#to plot the cdf function I need to generate a discrete interval
x<-seq(from = 1, to = 2, length = 100 )
plot(x,cf_2(x), type="l", col="red",xlab="Space [Km]", main = "Cumulative density function")
grid()


#quantile function 
#inverse <- function (f, lower = 1, upper = 2) {function (y) uniroot((function (x) f(x) - y), lower = lower, upper = upper)[1]}   #the inverse of a function 
qf_2 <- inverse(function(x) {integrate(df_2, lower = 1, upper = x)$value})                                                         #the inverse of cumulative function in one specific point 


#sampling function
rf_2<- function(nsamples){                                                                                                        #return a vector with samples following the pdf
  y <- c()
  for (i in 1:nsamples){
    u <- runif(1,0,1)
    y[i]<-qf_2(u)$root
    }
  return(y)
}
hist(rf_2(10000),breaks=30, xlab = "Space [Km]", main = "Histogram of 1000 simulated samples following the PDF",  col = 'skyblue3')    #an histo to check if it is following correcly the pdf 

```

```{r}
#determine the probability that tires will last less than 15000 km
prob_1 <- integrate(df_2, lower=-Inf, upper=1.5)
sprintf("The probability that tires will last less than 15000 km is : %f", prob_1$value)
```
```{r}
#sample 3000 random variables from the distribution and determine the mean value and the variance, using the expression V ar(X) = E[X 2 ] − E[X] 2
samples<-rf(3000)
sprintf("The mean value is: %f", mean(samples))
sprintf("The variance value is: %f", mean(samples**2)-(mean(samples))**2)
```








