```{r}
#EXERCISE 1
#plot the function, given the interval (a, b)
a <- 1
b <- 2
c <- 1.5 #eventually to acquire from terminal(?)

f <- function(x){(x < a)*(0)+(a <= x & x < c)*((2*(x-a))/((b-a)*(c-a)))+(c <= x & x <= b)*((2*(b-x))/((b-a)*(b-c)))+ (b < x)*(0)}
plot(f,xlim=c(a-1,b+1), ylim = c(-1, 3), col = "red",  xlab="Time [Hours]", ylab = "df(x)",main = "Triangular distribution function") 
grid()
```
```{r}
#and write an algorithm to generate random numbers from the triangular distribution

#since the function is already normalized it doesn't need to be done
#quantile function 
inverse <- function (f, lower = a, upper = b) {function (y) uniroot((function (x) f(x) - y), lower = lower, upper = upper)[1]}     #the inverse of a function 
qf <- inverse(function(x) {integrate(f, lower = a, upper = x)$value})                                                             #the inverse of cumulative function in one specific point 

#sampling function
rf<- function(nsamples){                                                                                                        #return a vector with samples following the pdf
  y <- c()
  for (i in 1:nsamples){
    u <- runif(1,0,1)
    y[i]<-qf(u)$root
    }
  return(y)
}
```

```{r}
#generate 10^4 random number from the distribution, show them in an histogram and superimpose the analytical curve
x <- rf(10000)
h <- hist(x,breaks=30, xlab = "Space [Km]", main = "Histogram of 10000 simulated samples following the Triangular distribution",  col = 'skyblue3')  
funct <- function(x){max(h$counts)*f(x)/2}
curve(funct, col="blue", lwd=2, add = TRUE) # add a densit y estimate with defaults
grid()

```



```{r}
#EXECISE 2
#plot G(k) and the Markov’s upper bound for the exponential, Exp(λ = 1), distribution function
lambda = 1
E <- 1/lambda                             #expectation value

g  <- function(k) {1- pexp(k, 1)}         #exponential distribution
M  <- function(k, E) {E/k}                #Markov's function

x <-seq(0, 10, 0.5)

plot(x, g(x), lwd=2.5, type = "b", pch="*", col="navy", main=expression(paste("Exponential distribution Exp(",lambda,"=1)")), cex.main=1.5, xlab="k", ylab="",cex.lab=1.5, las=1)

curve(M(x, E), from=0, to=10, lwd=2, col="cyan3", add=TRUE)

legend(6,1, legend=c("Markov's limit", expression(paste("P( X ">=" k ) "))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()
```
```{r}
#plot G(k) and the Markov’s upper bound for the uniform, U (3, 5), distribution function
a <- 3
b <- 5
E <- (a+b)/2                              #expectation value

g  <- function(k) {1- punif(k, a, b)}     #exponential distribution
M  <- function(k, E) {E/k}                #Markov's function

x <-seq(0, 10, 0.5)

plot(x, g(x), lwd=2.5, type = "b", pch="*", col="navy", main=expression(paste("Uniform distribution U(3,5)")), cex.main=1.5, xlab="k", ylab="",cex.lab=1.5, las=1)

curve(M(x, E), from=0, to=10, lwd=2, col="cyan3", add=TRUE)

legend(0,0.4, legend=c("Markov's limit", expression(paste("P( X ">=" k ) "))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()
```

```{r}
#plot G(k) and the Markov’s upper bound for the binomial, Bin(n = 1, p = 1/2), distribution function
n <- 1
p <- 1/2
E <- n*p                                #expectation value

g  <- function(k) {1- pbinom(k, n, p)}     #exponential distribution
M  <- function(k, E) {E/k}                #Markov's function

x <-seq(0, 10, 0.5)

plot(x, g(x), lwd=2.5, type = "b", pch="*", col="navy", main=expression(paste("Binomial distribution U(n=",1,", p=",0.5,")")), cex.main=1.5, xlab="k", ylab="",cex.lab=1.5, las=1)

curve(M(x, E), from=0, to=10, lwd=2, col="cyan3", add=TRUE)

legend(6,0.4, legend=c("Markov's limit", expression(paste("P( X ">=" k ) "))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()
```

```{r}
#plot G(k) and the Markov’s upper bound for a Poisson, Pois(λ = 1/2), distribution function

lambda <- 1/2
E <- lambda
                              #expectation value

g  <- function(k) {1- ppois(k, lambda)}     #exponential distribution
M  <- function(k, E) {E/k}                #Markov's function

x <-seq(0, 10, 0.5)

plot(x, g(x), lwd=2.5, type = "b", pch="*", col="navy", main=expression(paste("Poisson distribution Pois (",lambda,"=",0.5,")")), cex.main=1.5, xlab="k", ylab="",cex.lab=1.5, las=1)

curve(M(x, E), from=0, to=10, lwd=2, col="cyan3", add=TRUE)

legend(6,0.4, legend=c("Markov's limit", expression(paste("P( X ">=" k ) "))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()

```










```{r}
#EXERCISE 3
#use R to show, with a plot, that Chebyshev’s inequality is is an upper bound to the normal distribution, N(μ = 3, σ = 5)
m <- 3
sig <- 5


g <- function(k, m, sig){pnorm(m+k*sig, m, sig)-pnorm(m-k*sig, m, sig)}
C <- function(k) {1- (1/k)^2}

k <- seq(0,5,0.1)

plot(k, g(k,m,sig), lwd=2.5, type = "b", pch="*", col="navy",
     main=expression(paste("Normal distribution N(",mu,"=3,",sigma,"=5)")), cex.main=1.5,
     xlab="k", ylab="", 
     cex.lab=1.5, las=1)

curve(C(x), from=0, to=5, lwd=2, col="cyan3", add=TRUE)

legend(3.5,0.25, legend=c("Chebyshev's limit", expression(paste("P ( | x - ",mu,"| < k ",sigma,")"))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()
```
```{r}
#use R to show, with a plot, that Chebyshev’s inequality is is an upper bound to the exponential distribution, Exp(λ = 1)
m <- 1/1
sig <- 1

g <- function(k, m, sig){pexp(m+k*sig, m, sig)-pexp(m-k*sig, m, sig)}
C <- function(k) {1- (1/k)^2}

k <- seq(0,5,0.1)

plot(k, g(k,m,sig), lwd=2.5, type = "b", pch="*", col="navy",
     main=expression(paste("Exponential distribution   Exp(",lambda,"=1)")), cex.main=1.5,
     xlab="k", ylab="", 
     cex.lab=1.5, las=1)

curve(C(x), from=0, to=5, lwd=2, col="cyan3", add=TRUE)

legend(3.5,0.25, legend=c("Chebyshev's limit", expression(paste("P ( | x - ",mu,"| < k ",sigma,")"))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()

```
```{r}
#use R to show, with a plot, that Chebyshev’s inequality is is an upper bound to the uniform distribution U (1 − √2, 1 +  √2)
m <- (1+sqrt(2))+(1-sqrt(2))/2
sig <- (1+sqrt(2))-(1-sqrt(2))/ sqrt(12)

g <- function(k, m, sig){punif(m+k*sig, m, sig)-punif(m-k*sig, m, sig)}
C <- function(k) {1- (1/k)^2}

k <- seq(0,3,0.05)

plot(k, g(k,m,sig), lwd=2.5, type = "b", pch="*", col="navy",
     main=expression(paste("Uniform distribution   U( 1 - ",sqrt(2),", 1 + ",sqrt(2),")")), cex.main=1.5,
     xlab="k", ylab="", 
     cex.lab=1.5, las=1)

curve(C(x), from=0, to=3, lwd=2, col="cyan3", add=TRUE)

legend(2,0.25, legend=c("Chebyshev's limit", expression(paste("P ( | x - ",mu,"| < k ",sigma,")"))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()

```
```{r}
#use R to show, with a plot, that Chebyshev’s inequality is is an upper bound to the Poisson, Pois(λ = 1/3), distribution function
lambda = 1/3
m <- lambda
sig <- sqrt(lambda)

g <- function(k, m, sig){ppois(m+k*sig, m)-ppois(m-k*sig, m)}
C <- function(k) {1 - (1/k)^2}

k <- seq(0,5,0.1)

plot(k, g(k,m,sig),xlim = c(0,5), ylim=c(0,1), lwd=2.5, type = "b", pch="*", col="navy",
     main=expression(paste("Poisson distribution   Pois( ",lambda," = 1 / 3 )")), cex.main=1.5,
     xlab="k", ylab="", 
     cex.lab=1.5, las=1)

curve(C(x), from=0, to=5, lwd=2, col="cyan3", add=TRUE)

legend(2,0.25, legend=c("Chebyshev's limit", expression(paste("P ( | x - ",mu,"| < k ",sigma,")"))),
       col=c("cyan3", "navy"), lty=c("solid", "dashed"), 
       bty='n', cex = 1)
grid()

```


















```{r}
#   write a program in R that:
#   1) allows the user to insert the color of a randomly extracted box and
#   3) prints on the standard output the probability of selecting each box
#   4) plots the probability for each box as a function of the extraction step


N <- 5;     #max label box
i <- 0:N;   #index of boxes
pii <- i/N; #probability to find a white ball in a box ---> vector ( 0, 0.2, 0.4, 0.6, 0.8, 1)
n <- 0;     #number of extraction 


s <- c()   #variable to store the extractions

ext <- 1   #variable representing the single extraction--> default value

PB0 <- c(1/6) #initial value of each box probability
PB1 <- c(1/6)
PB2 <- c(1/6)
PB3 <- c(1/6)
PB4 <- c(1/6)
PB5 <- c(1/6)

while(ext != 2){ 

   par(mfrow=c(2,3))
   plot(0:n,PB0, main="BOX: H0", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
   plot(0:n,PB1, main="BOX: H1", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
   plot(0:n,PB2, main="BOX: H2", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
   plot(0:n,PB3, main="BOX: H3", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
   plot(0:n,PB4, main="BOX: H4", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
   plot(0:n,PB5, main="BOX: H5", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
   grid()
  
  ext <- readline(prompt="Enter the extraction, 0 black, 1 white, 2 to stop: ")
  ext <- as.integer(ext)
  if (ext != 2) {
    n <- n + 1
    s <- append(s, ext)
  
    x <-sum(s)      #tot number of white extractions
    PBi <- pii^x * (1-pii)^(n-x) / sum( pii^x * (1-pii)^(n-x) )     #vector: probability for single boxes at the n-th iteration  
    cat("The probability to having select each box from 0 to 5 is: ",PBi)
  
    PB0 <- append(PB0, PBi[1])   #storing probabilities
    PB1 <- append(PB1, PBi[2])
    PB2 <- append(PB2, PBi[3])
    PB3 <- append(PB3, PBi[4])
    PB4 <- append(PB4, PBi[5])
    PB5 <- append(PB5, PBi[6])
  }
  
}




```










```{r}
# write a simulation program that:
# 1) selects a random box
# 2) makes random sampling from the box
# 3) prints on the standard output the probability of selecting each box
# 4) plots the probability for each box as a function of the number of trial

N <- 5;                 #max label box
i <- 0:N;               #index for boxes
pii <- i/N;             #probability to find a white ball in a box ---> vector ( 0, 0.2, 0.4, 0.6, 0.8, 1)
ri <- sample(1:6, 1)    #random number for box selection
cat("Extracted box number:",ri,"\n")

n <- 100;               #number of total extractions from box ri

ext <- rbinom(n,1,pii[ri])   #variable representing the extractions ---> vector of 0 and 1
cat("Extracted colours are: (1 for white, 0 for black)\n",ext, "\n")

PB0 <- c(1/6)  #initial values of each box probability
PB1 <- c(1/6)
PB2 <- c(1/6)
PB3 <- c(1/6)
PB4 <- c(1/6)
PB5 <- c(1/6)

for (i in 1:n){

    
    x <-sum(ext[1:i])
    PBi <- pii^x * (1-pii)^(i-x) / sum( pii^x * (1-pii)^(i-x) )
    cat("The probability to having select each box from 0 to 5 is: ",PBi,"\n")
  
    PB0 <- append(PB0, PBi[1])
    PB1 <- append(PB1, PBi[2])
    PB2 <- append(PB2, PBi[3])
    PB3 <- append(PB3, PBi[4])
    PB4 <- append(PB4, PBi[5])
    PB5 <- append(PB5, PBi[6])
  
}

par(mfrow=c(2,3))
plot(0:n,PB0, main="BOX: H0", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()
plot(0:n,PB1, main="BOX: H1", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()
plot(0:n,PB2, main="BOX: H2", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()
plot(0:n,PB3, main="BOX: H3", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()
plot(0:n,PB4, main="BOX: H4", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()
plot(0:n,PB5, main="BOX: H5", cex.main=1.5 ,ylab = "Probability(Box)", xlab = "N of extraction", ylim = c(0:1), pch=16, cex=1.5, col="navy")
grid()


```









